backend:
  name: git-gateway
  branch: main # Cambia esto a la rama principal de tu repositorio

media_folder: "uploads" # Carpeta donde se guardarán las imágenes
public_folder: "/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Images", name: "images", widget: "image", multiple: true }